package org.executequery.gui.browser;

import org.executequery.databasemediators.DatabaseConnection;
import org.executequery.databaseobjects.NamedObject;
import org.executequery.gui.LoggingOutputPanel;
import org.executequery.gui.browser.comparer.Comparer;
import org.executequery.gui.text.SimpleSqlTextPanel;
import org.executequery.localization.Bundles;
import org.executequery.repository.DatabaseConnectionRepository;
import org.executequery.repository.RepositoryCache;
import org.underworldlabs.swing.layouts.GridBagHelper;

import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import java.awt.*;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ComparerDBPanel extends JPanel {

    public ComparerDBPanel() {
        initComponents();

        //jTextArea2.setLineWrap(true);

        logPanel.append("1st DB is an example - 2nd DB will be modified" + '\n'
                + "Start with connecting to DBs");
        dcs = new ArrayList<DatabaseConnection>();
        dbBox1.removeAllItems();
        dbBox2.removeAllItems();
        List<DatabaseConnection> connections = ((DatabaseConnectionRepository) RepositoryCache.load(DatabaseConnectionRepository.REPOSITORY_ID)).findAll();
        for (DatabaseConnection dc : connections) {
            if (dc.isConnected()) {
                dcs.add(dc);
                dbBox1.addItem(dc.getName());
                dbBox2.addItem(dc.getName());
            }
        }

    }

    Comparer comparer;
    List<DatabaseConnection> dcs;
    public static final String TITLE = Bundles.get(ComparerDBPanel.class, "ComparerDB");
    public static final String FRAME_ICON = "ComparerDB_16.png";

    public class FileTypeFilter extends FileFilter {

        private final String extension;
        private final String description;

        public FileTypeFilter(String extension, String description) {
            this.extension = extension;
            this.description = description;
        }

        public boolean accept(File file) {
            if (file.isDirectory()) {
                return true;
            }
            return file.getName().endsWith(extension);
        }

        public String getDescription() {
            return description + String.format(" (*%s)", extension);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logPanel = new LoggingOutputPanel();
        btnSaveScript = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        sqlTextPanel2 = new SimpleSqlTextPanel();
        checkBoxMap = new HashMap<>();
        for (Integer i = 0; i < NamedObject.SYSTEM_DOMAIN; i++) {
            JCheckBox checkBox = new JCheckBox(Bundles.get(NamedObject.class, NamedObject.META_TYPES_FOR_BUNDLE[i]));
            checkBoxMap.put(i, checkBox);
        }
        dbBox1 = new JComboBox();
        dbBox2 = new JComboBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Connections"));


        GridBagHelper gbh = new GridBagHelper();
        gbh.setDefaults(GridBagHelper.DEFAULT_CONSTRAINTS);
        gbh.defaults();
        jPanel1.setLayout(new GridBagLayout());
        gbh.addLabelFieldPair(jPanel1, "First connection", dbBox1, null);
        gbh.addLabelFieldPair(jPanel1, "Second connection", dbBox2, null);

        btnSaveScript.setText("Save script");
        btnSaveScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveScriptActionPerformed(evt);
            }
        });


        jButton1.setText("Compare");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));


        jButton2.setText("All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        gbh.defaults().setXY(0, 0);
        jPanel2.setLayout(new GridBagLayout());
        jPanel2.add(jButton2, gbh.setLabelDefault().get());
        for (JCheckBox checkBox : checkBoxMap.values()) {
            jPanel2.add(checkBox, gbh.nextRowFirstCol().setLabelDefault().get());
        }

        JScrollPane scroll = new JScrollPane(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSaveScript, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8))
                                        .addComponent(logPanel, GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                )
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sqlTextPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSaveScript)
                                        .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logPanel))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sqlTextPanel2)
                                        .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

    }// </editor-fold>//GEN-END:initComponents


    //GEN-LAST:event_btnConnectDBActionPerformed

    private void btnSaveScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveScriptActionPerformed
        /*String s = "";

         for (int i = 0; i < comparer.script.size(); i++){
         s = s + comparer.script.get(i);
         }

         try{
         BufferedWriter w = new BufferedWriter(new OutputStreamWriter(new FileOutputStream("output_file.txt"), "Cp1251"));
         w.write(s);
         w.flush();
         w.close();}
         catch(IOException ex){}*/

        if (comparer == null) {
            logPanel.append("\nNothing to save - script is empty");
            return;
        }
        if (comparer.script.isEmpty()) {
            logPanel.append("\nNothing to save - script is empty");
            return;
        }

        JFileChooser filesave = new JFileChooser("C:\\");

        //FileNameExtensionFilter filter = new FileNameExtensionFilter("*.*");
        //filesave.setFileFilter(filter);
        FileFilter sqlFilter = new FileTypeFilter(".sql", "SQL files");
        FileFilter txtFilter = new FileTypeFilter(".txt", "Text files");

        filesave.addChoosableFileFilter(sqlFilter);
        filesave.addChoosableFileFilter(txtFilter);
        filesave.setAcceptAllFileFilterUsed(false);

        int ret = filesave.showDialog(null, "Save Script");

        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = filesave.getSelectedFile();

            String text, n = "\n";

            String name = file.getAbsoluteFile().toString();

            int dot = name.lastIndexOf(".");
            dot = dot == -1 ? name.length() : dot;

            String name_ = name.substring(0, dot)
                    + filesave.getFileFilter().getDescription().substring(filesave.getFileFilter().getDescription().indexOf("(*") + 2,
                    filesave.getFileFilter().getDescription().lastIndexOf(")"));
            comparer.script.add("русский текст");
            try (FileOutputStream path = new FileOutputStream(name_)) {
                for (int i = 0; i < comparer.script.size(); i++) {
                    text = comparer.script.get(i);

                    //String str = new String(text.getBytes(), "Cp1251");
                    byte[] buffer = text.getBytes();

                    path.write(buffer, 0, buffer.length);

                    /*byte[] bufferN = n.getBytes();
                     path.write(bufferN, 0, bufferN.length);*/
                }

                logPanel.append("\nScript was saved:\n" + "«" + name_ + "»");
            } catch (IOException ex) {

                System.out.println(ex.getMessage());
            }
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (dcs.size() < 2 || dbBox1.getSelectedIndex() == dbBox2.getSelectedIndex()) {
            logPanel.append("\nError: Unable to compare");
            return;
        }
        comparer = new Comparer(dcs.get(dbBox1.getSelectedIndex()), dcs.get(dbBox2.getSelectedIndex()));
        logPanel.append("\nComparing...\n");

        sqlTextPanel2.setSQLText("");
        comparer.script.clear();
        comparer.createdObjects.clear();
        comparer.alteredObjects.clear();
        comparer.droppedObjects.clear();


        String charset = "";
        String dialect = "";

        String query = "select rdb$database.rdb$character_set_name\n"
                + "from rdb$database\n";

        try {
            ResultSet rs = comparer.secondConnection.execute(query, true).getResultSet();

            while (rs.next()) {

                charset = rs.getString(1).trim();
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e);
        } finally {
            comparer.secondConnection.releaseResources();
        }

        query = "select mon$database.mon$sql_dialect\n"
                + "from mon$database\n";

        try {
            ResultSet rs = comparer.secondConnection.execute(query, true).getResultSet();

            while (rs.next()) {

                dialect = rs.getString(1).trim();
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e);
        } finally {
            comparer.secondConnection.releaseResources();
        }

        comparer.script.add("set names " + charset + ";\n\n");
        comparer.script.add("set sql dialect " + dialect + ";\n\n");
        comparer.script.add("connect '" + comparer.secondConnection.getDatabaseConnection().getName() + " ' user '" + comparer.secondConnection.getDatabaseConnection().getUserName() + "' "
                + "password '" + comparer.secondConnection.getDatabaseConnection().getUnencryptedPassword() + "';\n\n");
        comparer.script.add("set autoddl on;\n\n");

        comparer.lists = "";
        /*comparer.dropFKs(jCheckBox12.isSelected());
        logPanel.append("\n============= Foreign keys to drop =============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropPKs(jCheckBox11.isSelected());
        logPanel.append("\n============= Primary keys to drop =============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropUniques(jCheckBox13.isSelected());
        logPanel.append("\n=============== Uniques to drop ===============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropChecks(jCheckBox14.isSelected());
        logPanel.append("\n=============== Checks to drop  ===============\n\n");
        logPanel.append(comparer.lists);*/
        for (Integer type : checkBoxMap.keySet()) {
            comparer.lists = "";
            comparer.createObjects(checkBoxMap.get(type).isSelected(), type);
            logPanel.append(MessageFormat.format("\n============= {0} to create  =============\n\n", Bundles.getEn(NamedObject.class, NamedObject.META_TYPES_FOR_BUNDLE[type])));
            logPanel.append(comparer.lists);

        }


        /*comparer.lists = "";
        comparer.alterExceptions(jCheckBox7.isSelected());
        logPanel.append("\n============== Exceptions to alter ==============\n\n");
        logPanel.append(comparer.lists);


        comparer.lists = "";
        comparer.alterGenerators(jCheckBox6.isSelected());
        logPanel.append("\n============== Generators to alter ==============\n\n");
        logPanel.append(comparer.lists);


        comparer.lists = "";
        comparer.alterUDFs(jCheckBox8.isSelected());
        logPanel.append("\n================ UDFs to alter ================\n\n");
        logPanel.append(comparer.lists);


        comparer.lists = "";
        comparer.alterDomains(jCheckBox2.isSelected());
        logPanel.append("\n=============== Domains to alter ===============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropIndices(jCheckBox10.isSelected());
        logPanel.append("\n================ Indices to drop  ===============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropTriggers(jCheckBox5.isSelected());
        logPanel.append("\n=============== Triggers to drop  ===============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropViews(jCheckBox3.isSelected());
        logPanel.append("\n================ Views to drop ================\n\n");
        logPanel.append(comparer.lists);


        comparer.lists = "";
        comparer.alterTables(jCheckBox1.isSelected());
        logPanel.append("\n================ Tables to alter ================\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropTables(jCheckBox1.isSelected());
        logPanel.append("\n================ Tables to drop ================\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.alterProcedures(jCheckBox4.isSelected());
        logPanel.append("\n============== Procedures to alter ==============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropProcedures(jCheckBox4.isSelected());
        logPanel.append("\n============== Procedures to drop  ==============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.createViews(jCheckBox3.isSelected());
        comparer.retViews(true);
        logPanel.append("\n================ Views to create  ===============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.alterViews(jCheckBox3.isSelected());
        logPanel.append("\n================= Views to alter ================\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.createChecks(jCheckBox14.isSelected());
        logPanel.append("\n=============== Checks to create  ===============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.alterChecks(jCheckBox14.isSelected());
        logPanel.append("\n================ Checks to alter ================\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.createUniques(jCheckBox13.isSelected());
        logPanel.append("\n=============== Uniques to create ===============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.alterUniques(jCheckBox13.isSelected());
        logPanel.append("\n================ Uniques to alter  ===============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.createPKs(jCheckBox11.isSelected());
        logPanel.append("\n============= Primary keys to create =============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.alterPKs(jCheckBox11.isSelected());
        logPanel.append("\n=============  Primary keys to alter ==============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.createFKs(jCheckBox12.isSelected());
        logPanel.append("\n============= Foreign keys to create =============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.alterFKs(jCheckBox12.isSelected());
        logPanel.append("\n============== Foreign keys to alter  =============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropDomains(jCheckBox2.isSelected());
        logPanel.append("\n=============== Domains to drop ===============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropUDFs(jCheckBox8.isSelected());
        logPanel.append("\n================ UDFs to drop  ================\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropExceptions(jCheckBox7.isSelected());
        logPanel.append("\n============== Exceptions to drop  ==============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.dropGenerators(jCheckBox6.isSelected());
        logPanel.append("\n============== Generators to drop  ==============\n\n");
        logPanel.append(comparer.lists);

        comparer.lists = "";
        comparer.alterTriggers(jCheckBox5.isSelected());
        logPanel.append("\n=============== Triggers to alter  ===============\n\n");
        logPanel.append(comparer.lists);

        comparer.computedField(true);
        comparer.fillViews(true);
        comparer.fillProcedures(true);
        comparer.fillTriggers(true);
        comparer.recreateChecks(true);

        comparer.lists = "";
        comparer.alterIndices(jCheckBox10.isSelected());
        logPanel.append("\n================ Indices to alter  ===============\n\n");
        logPanel.append(comparer.lists);

        comparer.fillIndices(true);

        comparer.lists = "";
        comparer.dropRoles(jCheckBox9.isSelected());
        logPanel.append("\n================ Roles to drop  ================\n\n");
        logPanel.append(comparer.lists);*/

        for (int i = 0; i < comparer.script.size(); i++) {
            //System.out.println(comparer.script.get(i));
            sqlTextPanel2.getTextPane().append(comparer.script.get(i));
        }
        /*for (int i = 0; i < comparer.warnings.size(); i++) {
         System.out.println(i + 1 + ": " + comparer.warnings.get(i));
         }*/


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean curFlag = true;
        for (JCheckBox checkBox : checkBoxMap.values()) {
            curFlag = curFlag && checkBox.isSelected();
        }
        for (JCheckBox checkBox : checkBoxMap.values()) {
            checkBox.setSelected(!curFlag);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    //GEN-LAST:event_btnInstall_libActionPerformed


    String bundleString(String key) {
        return Bundles.get(ComparerDBPanel.class, key);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton btnSaveScript;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private LoggingOutputPanel logPanel;
    private SimpleSqlTextPanel sqlTextPanel2;
    private javax.swing.JComboBox dbBox1;
    private javax.swing.JComboBox dbBox2;
    private Map<Integer, JCheckBox> checkBoxMap;

    // End of variables declaration//GEN-END:variables

}
