/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.executequery.gui.browser;

import biz.redsoft.IFBUser;
import biz.redsoft.IFBUserManager;
import org.executequery.GUIUtilities;
import org.executequery.components.table.BrowserTableCellRenderer;
import org.executequery.components.table.RoleTableModel;
import org.executequery.databasemediators.DatabaseConnection;
import org.executequery.datasource.ConnectionManager;
import org.executequery.gui.browser.BrowserConstants;
import org.executequery.gui.browser.managment.ThreadOfGrantManager;
import org.executequery.log.Log;
import org.executequery.repository.DatabaseConnectionRepository;
import org.executequery.repository.RepositoryCache;
import org.underworldlabs.util.MiscUtils;

import javax.swing.*;
import java.awt.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Map;
import java.util.Vector;

/**
 * @author mikhan808
 */
public class GrantManagerPanel extends JPanel {

    /**
     * Creates new form GrantManagerPanel
     */
    public GrantManagerPanel() {
        gr = GUIUtilities.loadIcon(BrowserConstants.GRANT_IMAGE);
        no = GUIUtilities.loadIcon(BrowserConstants.NO_GRANT_IMAGE);
        adm = GUIUtilities.loadIcon(BrowserConstants.ADMIN_OPTION_IMAGE);
        enableElements = true;
        enabled_dBox = false;
        initComponents();
        relName = new Vector<>();
        relType = new Vector<>();
        relSystem = new Vector<Boolean>();
        relGranted = new Vector<Boolean>();
        fieldName = new Vector<>();
        fieldType = new Vector<>();
        BrowserTableCellRenderer bctr = new BrowserTableCellRenderer();
        tablePrivileges.setDefaultRenderer(Object.class, bctr);
        jTable2.setDefaultRenderer(Object.class, bctr);
        enabled_dBox = true;
        setEnableElements(true);
        load_connections();
        load_userList();


    }

    public static final String TITLE = "Grant manager";
    public static final String FRAME_ICON = "grant_manager_16.png";
    List<DatabaseConnection> listConnections;
    Connection con;
    //Statement state;
    //ResultSet rs;
    DefaultListModel userlistModel;
    boolean enabled_dBox;
    boolean enableElements;
    Vector<String> relName;
    Vector<String> relType;
    Vector<Boolean> relSystem;
    Vector<Boolean> relGranted;
    String grants = "SUDIXRGA";
    String[] headers = {"Object", "Select", "Update", "Delete", "Insert", "Execute", "References", "Usage"};
    String[] headers2 = {"Field", "Type", "Update", "References"};
    Icon gr, no, adm;
    Action act;
    Vector<String> fieldName;
    Vector<String> fieldType;
    int obj_index;

    enum Action {
        NO_ALL_GRANTS_TO_OBJECT,
        ALL_GRANTS_TO_OBJECT,
        ALL_GRANTS_TO_OBJECT_WITH_GRANT_OPTION,
        NO_GRANT_TO_ALL_OBJECTS,
        GRANT_TO_ALL_OBJECTS,
        GRANT_TO_ALL_OBJECTS_WITH_GRANT_OPTION,
        NO_ALL_GRANTS_TO_ALL_OBJECTS,
        ALL_GRANTS_TO_ALL_OBJECTS,
        ALL_GRANTS_TO_ALL_OBJECTS_WITH_GRANT_OPTION,
        CREATE_TABLE

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upPanel = new JPanel();
        databaseBox = new JComboBox<>();
        refreshButton = new JButton();
        leftPanel = new JPanel();
        jLabel1 = new JLabel();
        userBox = new JComboBox<>();
        jScrollPane1 = new JScrollPane();
        userList = new JList<>();
        rightPanel = new JPanel();
        jLabel2 = new JLabel();
        revoke_v = new JButton();
        revoke_g = new JButton();
        revoke_all = new JButton();
        grant_v = new JButton();
        grant_g = new JButton();
        grant_all = new JButton();
        grant_option_v = new JButton();
        grant_option_g = new JButton();
        grant_option_all = new JButton();
        objectBox = new JComboBox<>();
        filterBox = new JComboBox<>();
        filterField = new JTextField();
        jCheckBox1 = new JCheckBox();
        systemCheck = new JCheckBox();
        jScrollPane2 = new JScrollPane();
        tablePrivileges = new JTable();
        downPanel = new JPanel();
        labelTable = new JLabel();
        revoke_v1 = new JButton();
        revoke_g1 = new JButton();
        grant_v1 = new JButton();
        grant_g1 = new JButton();
        grant_option_v1 = new JButton();
        grant_option_g1 = new JButton();
        jScrollPane3 = new JScrollPane();
        jTable2 = new JTable();
        jProgressBar1 = new JProgressBar();
        cancelButton = new JButton();

        databaseBox.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        databaseBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseBoxActionPerformed(evt);
            }
        });

        refreshButton.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/Refresh16.png"))); // NOI18N
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        GroupLayout upPanelLayout = new GroupLayout(upPanel);
        upPanel.setLayout(upPanelLayout);
        upPanelLayout.setHorizontalGroup(
                upPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(upPanelLayout.createSequentialGroup()
                                .addComponent(databaseBox, GroupLayout.PREFERRED_SIZE, 203, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(refreshButton, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        upPanelLayout.setVerticalGroup(
                upPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(databaseBox, GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(refreshButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setText("Priveleges for");
        jLabel1.setOpaque(true);

        userBox.setModel(new DefaultComboBoxModel<>(new String[]{"Users", "Roles", "Views", "Triggers", "Procedures"}));
        userBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBoxActionPerformed(evt);
            }
        });

        userList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                userListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(userList);

        GroupLayout leftPanelLayout = new GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
                leftPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING)
        );
        leftPanelLayout.setVerticalGroup(
                leftPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(leftPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
        );

        jLabel2.setText("Grants on");
        jLabel2.setOpaque(true);

        revoke_v.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/no_grant_vertical.png"))); // NOI18N
        revoke_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revoke_vActionPerformed(evt);
            }
        });

        revoke_g.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/no_grant_gorisont.png"))); // NOI18N
        revoke_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revoke_gActionPerformed(evt);
            }
        });

        revoke_all.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/no_grant_all.png"))); // NOI18N
        revoke_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revoke_allActionPerformed(evt);
            }
        });

        grant_v.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/grant_vertical.png"))); // NOI18N
        grant_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grant_vActionPerformed(evt);
            }
        });

        grant_g.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/grant_gorisont.png"))); // NOI18N
        grant_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grant_gActionPerformed(evt);
            }
        });

        grant_all.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/grant_all.png"))); // NOI18N
        grant_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grant_allActionPerformed(evt);
            }
        });

        grant_option_v.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/admin_option_vertical.png"))); // NOI18N
        grant_option_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grant_option_vActionPerformed(evt);
            }
        });

        grant_option_g.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/admin_option_gorisont.png"))); // NOI18N
        grant_option_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grant_option_gActionPerformed(evt);
            }
        });

        grant_option_all.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/admin_option_all.png"))); // NOI18N
        grant_option_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grant_option_allActionPerformed(evt);
            }
        });

        objectBox.setModel(new DefaultComboBoxModel<>(new String[]{"All objects", "Tables", "Views", "Procedures"}));
        objectBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objectBoxActionPerformed(evt);
            }
        });

        filterBox.setModel(new DefaultComboBoxModel<>(new String[]{"Display all", "Granted only", "Non-granted only"}));
        filterBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBoxActionPerformed(evt);
            }
        });

        filterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterFieldActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Invert filter");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        systemCheck.setText("Show system tables");
        systemCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemCheckActionPerformed(evt);
            }
        });

        tablePrivileges.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{

                }
        ));
        tablePrivileges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePrivilegesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePrivileges);

        labelTable.setText("Columns of ");
        labelTable.setOpaque(true);

        revoke_v1.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/no_grant_vertical.png"))); // NOI18N
        revoke_v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revoke_v1ActionPerformed(evt);
            }
        });

        revoke_g1.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/no_grant_gorisont.png"))); // NOI18N
        revoke_g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revoke_g1ActionPerformed(evt);
            }
        });

        grant_v1.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/grant_vertical.png"))); // NOI18N
        grant_v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grant_v1ActionPerformed(evt);
            }
        });

        grant_g1.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/grant_gorisont.png"))); // NOI18N
        grant_g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grant_g1ActionPerformed(evt);
            }
        });

        grant_option_v1.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/admin_option_vertical.png"))); // NOI18N
        grant_option_v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grant_option_v1ActionPerformed(evt);
            }
        });

        grant_option_g1.setIcon(new ImageIcon(getClass().getResource("/org/executequery/icons/admin_option_gorisont.png"))); // NOI18N
        grant_option_g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grant_option_g1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{

                }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        GroupLayout downPanelLayout = new GroupLayout(downPanel);
        downPanel.setLayout(downPanelLayout);
        downPanelLayout.setHorizontalGroup(
                downPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(labelTable, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(downPanelLayout.createSequentialGroup()
                                .addComponent(revoke_v1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(revoke_g1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grant_v1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grant_g1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grant_option_v1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grant_option_g1)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane3, GroupLayout.Alignment.TRAILING)
        );
        downPanelLayout.setVerticalGroup(
                downPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(downPanelLayout.createSequentialGroup()
                                .addComponent(labelTable, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(downPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(downPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addComponent(revoke_v1)
                                                .addComponent(revoke_g1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(grant_v1, GroupLayout.Alignment.TRAILING)
                                                .addComponent(grant_g1, GroupLayout.Alignment.TRAILING))
                                        .addComponent(grant_option_v1, GroupLayout.Alignment.TRAILING)
                                        .addComponent(grant_option_g1, GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE))
        );

        cancelButton.setText("Cancel fill");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        GroupLayout rightPanelLayout = new GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
                rightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addComponent(downPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rightPanelLayout.createSequentialGroup()
                                .addGroup(rightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(rightPanelLayout.createSequentialGroup()
                                                .addGroup(rightPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(objectBox, GroupLayout.Alignment.LEADING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(rightPanelLayout.createSequentialGroup()
                                                                .addComponent(revoke_v)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(revoke_g)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(revoke_all)))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(rightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(rightPanelLayout.createSequentialGroup()
                                                                .addComponent(grant_v)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(grant_g)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(grant_all)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(grant_option_v))
                                                        .addComponent(filterBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(rightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(rightPanelLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(grant_option_g)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(grant_option_all)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(rightPanelLayout.createSequentialGroup()
                                                                .addGap(9, 9, 9)
                                                                .addGroup(rightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(rightPanelLayout.createSequentialGroup()
                                                                                .addComponent(jCheckBox1)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(cancelButton))
                                                                        .addComponent(filterField)))))
                                        .addGroup(rightPanelLayout.createSequentialGroup()
                                                .addGroup(rightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(systemCheck)
                                                        .addComponent(jProgressBar1, GroupLayout.PREFERRED_SIZE, 900, GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        rightPanelLayout.setVerticalGroup(
                rightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(rightPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(rightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(rightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addComponent(revoke_v)
                                                .addComponent(revoke_g, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(revoke_all)
                                                .addComponent(grant_v)
                                                .addComponent(grant_g))
                                        .addComponent(grant_all)
                                        .addComponent(grant_option_v)
                                        .addComponent(grant_option_g)
                                        .addComponent(grant_option_all))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(rightPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(objectBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(filterBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(filterField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(rightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(rightPanelLayout.createSequentialGroup()
                                                .addGroup(rightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jCheckBox1, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(systemCheck))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(rightPanelLayout.createSequentialGroup()
                                                        .addComponent(jProgressBar1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cancelButton))))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 247, GroupLayout.DEFAULT_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(downPanel, GroupLayout.PREFERRED_SIZE, 142, GroupLayout.PREFERRED_SIZE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(upPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(leftPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rightPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(upPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(rightPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(leftPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void databaseBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseBoxActionPerformed
        // TODO add your handling code here:
        if (enabled_dBox)
            con = ConnectionManager.getConnection(listConnections.get(databaseBox.getSelectedIndex()));
    }//GEN-LAST:event_databaseBoxActionPerformed

    private void userBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBoxActionPerformed
        // TODO add your handling code here:
        load_userList();
    }//GEN-LAST:event_userBoxActionPerformed

    private void userListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_userListValueChanged
        // TODO add your handling code here:
        if (userlistModel.size() > 0)
            if (userList.getSelectedValue() != null) {
                act = Action.CREATE_TABLE;
                execute_thread();
            }
    }//GEN-LAST:event_userListValueChanged

    private void objectBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objectBoxActionPerformed
        // TODO add your handling code here:
        act = Action.CREATE_TABLE;
        execute_thread();
    }//GEN-LAST:event_objectBoxActionPerformed

    private void filterBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBoxActionPerformed
        // TODO add your handling code here:
        act = Action.CREATE_TABLE;
        execute_thread();
    }//GEN-LAST:event_filterBoxActionPerformed

    private void filterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterFieldActionPerformed
        // TODO add your handling code here:
        act = Action.CREATE_TABLE;
        execute_thread();
    }//GEN-LAST:event_filterFieldActionPerformed

    private void systemCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemCheckActionPerformed
        // TODO add your handling code here:
        act = Action.CREATE_TABLE;
        execute_thread();
    }//GEN-LAST:event_systemCheckActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        act = Action.CREATE_TABLE;
        execute_thread();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setEnableElements(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        load_userList();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void revoke_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revoke_vActionPerformed
        // TODO add your handling code here:
        act = Action.NO_GRANT_TO_ALL_OBJECTS;
        execute_thread();
    }//GEN-LAST:event_revoke_vActionPerformed

    private void revoke_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revoke_gActionPerformed
        // TODO add your handling code here:
        int row = tablePrivileges.getSelectedRow();
        if (row >= 0) {
            for (int col = 1; col < headers.length; col++) {
                grant_on_role(0, row, col);
            }
        }

    }//GEN-LAST:event_revoke_gActionPerformed

    private void revoke_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revoke_allActionPerformed
        // TODO add your handling code here:
        act = Action.NO_ALL_GRANTS_TO_ALL_OBJECTS;
        execute_thread();
    }//GEN-LAST:event_revoke_allActionPerformed

    private void grant_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grant_vActionPerformed
        // TODO add your handling code here:
        act = Action.GRANT_TO_ALL_OBJECTS;
        execute_thread();
    }//GEN-LAST:event_grant_vActionPerformed

    private void grant_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grant_gActionPerformed
        // TODO add your handling code here:
        int row = tablePrivileges.getSelectedRow();
        if (row >= 0) {
            for (int col = 1; col < headers.length; col++) {
                grant_on_role(1, row, col);
            }
        }
    }//GEN-LAST:event_grant_gActionPerformed

    private void grant_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grant_allActionPerformed
        // TODO add your handling code here:
        act = Action.ALL_GRANTS_TO_ALL_OBJECTS;
        execute_thread();
    }//GEN-LAST:event_grant_allActionPerformed

    private void grant_option_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grant_option_vActionPerformed
        // TODO add your handling code here:
        act = Action.GRANT_TO_ALL_OBJECTS_WITH_GRANT_OPTION;
        execute_thread();
    }//GEN-LAST:event_grant_option_vActionPerformed

    private void grant_option_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grant_option_gActionPerformed
        // TODO add your handling code here:
        int row = tablePrivileges.getSelectedRow();
        if (row >= 0) {
            for (int col = 1; col < headers.length; col++) {
                grant_on_role(2, row, col);
            }
        }
    }//GEN-LAST:event_grant_option_gActionPerformed

    private void grant_option_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grant_option_allActionPerformed
        // TODO add your handling code here:
        act = Action.ALL_GRANTS_TO_ALL_OBJECTS_WITH_GRANT_OPTION;
        execute_thread();
    }//GEN-LAST:event_grant_option_allActionPerformed

    private void tablePrivilegesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePrivilegesMouseClicked
        // TODO add your handling code here:
        if (enableElements) {
            int row = tablePrivileges.getSelectedRow();
            if (evt.getClickCount() > 1) {
                int col = tablePrivileges.getSelectedColumn();
                if (col > 0) {
                    if (((Icon) tablePrivileges.getValueAt(row, col)).equals(gr)) {


                        grant_on_role(2, row, col);


                    } else if (((Icon) tablePrivileges.getValueAt(row, col)).equals(adm)) {

                        grant_on_role(0, row, col);

                    } else {

                        grant_on_role(1, row, col);

                    }
                }
            }
            if (row >= 0) {
                setVisiblePanelOfTable(!relType.elementAt(row).equals(objectBox.getItemAt(3)));
            }
        }
    }//GEN-LAST:event_tablePrivilegesMouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        if (enableElements) {
            int row = tablePrivileges.getSelectedRow();
            int row2 = jTable2.getSelectedRow();
            if (evt.getClickCount() > 1) {
                int col = jTable2.getSelectedColumn();
                if (col > 1) {
                    if (((Icon) jTable2.getValueAt(row2, col)).equals(gr)) {


                        grant_on_role(2, row, col, row2);


                    } else if (((Icon) jTable2.getValueAt(row2, col)).equals(adm)) {

                        grant_on_role(0, row, col, row2);

                    } else {

                        grant_on_role(1, row, col, row2);

                    }
                }
            }

        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void revoke_v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revoke_v1ActionPerformed
        // TODO add your handling code here:
        int col = jTable2.getSelectedColumn();
        int row2 = obj_index;
        if (col > 1)
            for (int row = 0; row < fieldName.size(); row++) {
                grant_on_role(0, row2, col, row);
            }
    }//GEN-LAST:event_revoke_v1ActionPerformed

    private void revoke_g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revoke_g1ActionPerformed
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        int row2 = obj_index;
        if (row >= 0)
            for (int col = 2; col < 4; col++) {
                grant_on_role(0, row2, col, row);
            }
    }//GEN-LAST:event_revoke_g1ActionPerformed

    private void grant_v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grant_v1ActionPerformed
        // TODO add your handling code here:
        int col = jTable2.getSelectedColumn();
        int row2 = obj_index;
        ;
        if (col > 1)
            for (int row = 0; row < fieldName.size(); row++) {
                grant_on_role(1, row2, col, row);
            }
    }//GEN-LAST:event_grant_v1ActionPerformed

    private void grant_g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grant_g1ActionPerformed
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        int row2 = obj_index;
        if (row >= 0)
            for (int col = 2; col < 4; col++) {
                grant_on_role(1, row2, col, row);
            }
    }//GEN-LAST:event_grant_g1ActionPerformed

    private void grant_option_v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grant_option_v1ActionPerformed
        // TODO add your handling code here:
        int col = jTable2.getSelectedColumn();
        int row2 = obj_index;
        if (col > 1)
            for (int row = 0; row < fieldName.size(); row++) {
                grant_on_role(2, row2, col, row);
            }
    }//GEN-LAST:event_grant_option_v1ActionPerformed

    private void grant_option_g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grant_option_g1ActionPerformed
        // TODO add your handling code here:

        int row = jTable2.getSelectedRow();
        int row2 = obj_index;
        if (row >= 0)
            for (int col = 2; col < 4; col++) {
                grant_on_role(2, row2, col, row);
            }
    }//GEN-LAST:event_grant_option_g1ActionPerformed

    void load_connections() {
        enabled_dBox = false;
        databaseBox.removeAllItems();
        listConnections = ((DatabaseConnectionRepository) RepositoryCache.load(DatabaseConnectionRepository.REPOSITORY_ID)).findAll();
        for (DatabaseConnection dc : listConnections) {
            if (dc.isConnected()) {
                databaseBox.addItem(dc.getName());
                enabled_dBox = true;
                databaseBox.setSelectedItem(dc.getName());
            } else {
                listConnections.remove(dc);
            }
        }
    }

    void load_userList() {
        userlistModel = new DefaultListModel();
        userList.setModel(userlistModel);
        int ind_userBox = userBox.getSelectedIndex();
        switch (ind_userBox) {
            case 0:
                get_users();
                break;
            case 1:
                get_roles();
                break;
            case 2:
                get_views_for_userlist();
                break;
            case 3:
                get_triggers_for_userlist();
                break;
            case 4:
                get_procedures_for_userlist();
                break;
            default:
                break;
        }
        if (userlistModel.size() > 0)
            userList.setSelectedIndex(0);
    }

    IFBUserManager getUserManager(IFBUserManager userManager, DatabaseConnection dc) {
        userManager.setDatabase(dc.getSourceName());
        userManager.setHost(dc.getHost());
        userManager.setPort(dc.getPortInt());
        userManager.setUser(dc.getUserName());
        userManager.setPassword(dc.getUnencryptedPassword());
        return userManager;
    }

    void get_users() {
        Connection connection = null;
        try {
            connection = con.unwrap(Connection.class);
        } catch (SQLException e) {
            e.printStackTrace();
        }

        URL[] urls = new URL[0];
        Class clazzdb = null;
        Object odb = null;
        try {
            urls = MiscUtils.loadURLs("./lib/fbplugin-impl.jar");
            ClassLoader cl = new URLClassLoader(urls, connection.getClass().getClassLoader());
            clazzdb = cl.loadClass("biz.redsoft.FBUserManagerImpl");
            odb = clazzdb.newInstance();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        IFBUserManager userManager = (IFBUserManager) odb;
        userManager = getUserManager(userManager, listConnections.get(databaseBox.getSelectedIndex()));
        Map<String, IFBUser> users;
        try {

            users = userManager.getUsers();
            for (IFBUser u : users.values()) {
                userlistModel.addElement(u.getUserName());
            }
            userlistModel.addElement("PUBLIC");
        } catch (Exception e) {
            System.out.println(e.toString());
            //GUIUtilities.displayErrorMessage(e.toString());
        }
    }

    void get_roles() {
        try {
            Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
            ResultSet result = st.executeQuery("SELECT RDB$ROLE_NAME FROM RDB$ROLES order by 1");
            while (result.next()) {
                String role = result.getString(1);
                userlistModel.addElement(role);


            }
            st.close();
            int i = 0;
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    void get_views_for_userlist() {
        try {
            Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
            String query = "Select RDB$RELATION_NAME from RDB$RELATIONS" +
                    " WHERE RDB$RELATION_TYPE = 1 order by 1";
            ResultSet result = st.executeQuery(query);
            while (result.next()) {
                String role = result.getString(1);
                userlistModel.addElement(role);
            }
            st.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    void get_triggers_for_userlist() {
        try {
            Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
            String query = "Select RDB$TRIGGER_NAME from RDB$TRIGGERS order by 1";
            ResultSet result = st.executeQuery(query);
            while (result.next()) {
                String role = result.getString(1);
                userlistModel.addElement(role);
            }
            st.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    void get_procedures_for_userlist() {
        try {
            Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
            String query = "Select RDB$PROCEDURE_NAME from RDB$PROCEDURES order by 1";
            ;
            ResultSet result = st.executeQuery(query);
            while (result.next()) {
                String role = result.getString(1);
                userlistModel.addElement(role);
            }
            st.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    void load_table() {

        tablePrivileges.setModel(new RoleTableModel(headers, 0));
        relName.removeAllElements();
        relType.removeAllElements();
        relSystem.removeAllElements();
        relGranted.removeAllElements();
        if (objectBox.getSelectedIndex() == 0 || objectBox.getSelectedIndex() == 1)
            getTables();
        if (objectBox.getSelectedIndex() == 0 || objectBox.getSelectedIndex() == 2)
            getViews();
        if (objectBox.getSelectedIndex() == 0 || objectBox.getSelectedIndex() == 3)
            getProcedures();
        jProgressBar1.setMaximum(relName.size());
        for (int i = 0, g = 0; i < relName.size() && !enableElements; g++, i++) {
            jProgressBar1.setValue(g);
            try {
                Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                String s = "select distinct RDB$PRIVILEGE,RDB$GRANT_OPTION from RDB$USER_PRIVILEGES\n" +
                        "where (rdb$Relation_name='" + relName.elementAt(i) + "') and (rdb$user='"
                        + userList.getSelectedValue().trim() + "') and (RDB$FIELD_NAME IS NULL)";
                ResultSet rs1 = st.executeQuery(s);
                Vector<Object> roleData = new Vector<Object>();
                Object[] obj = {relName.elementAt(i), Color.BLACK};
                if (relSystem.elementAt(i))
                    obj[1] = Color.RED;
                roleData.add(obj);
                for (int k = 0; k < 7; k++)
                    roleData.add(no);
                boolean adding = true;
                while (rs1.next()) {
                    relGranted.set(i, true);
                    if (filterBox.getSelectedIndex() == 0 || (filterBox.getSelectedIndex() == 1) == relGranted.elementAt(i)) {
                        try {
                            String grant = rs1.getString(1).trim();
                            int ind = grants.indexOf(grant);
                            if (ind != 7) {
                                Object gr_opt = rs1.getObject(2);
                                if (gr_opt == null)
                                    gr_opt = 0;
                                if (gr_opt.equals(0)) {
                                    roleData.set(ind + 1, gr);
                                } else
                                    roleData.set(ind + 1, adm);
                            }
                        } catch (Exception e) {
                            Log.error(e.getMessage());
                        }
                    } else {
                        removeRow(i);
                        i--;
                        adding = false;
                        break;
                    }
                }
                if (adding) ((RoleTableModel) tablePrivileges.getModel()).addRow(roleData);
                st.close();
            } catch (Exception e) {
                GUIUtilities.displayErrorMessage(e.getMessage());
            }
        }
        setEnableElements(true);
        setVisiblePanelOfTable(false);

    }

    void load_table2(String rname) {
        jTable2.setModel(new RoleTableModel(headers2, 0));
        fieldName = new Vector<>();
        fieldType = new Vector<>();
        try {
            Statement state = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
            String query = "Select RF.RDB$FIELD_NAME,F.RDB$FIELD_TYPE\n" +
                    "from RDB$RELATION_FIELDS AS RF left join RDB$FIELDS AS F\n" +
                    "ON F.RDB$FIELD_NAME=RF.RDB$FIELD_SOURCE\n" +
                    "WHERE RF.RDB$RELATION_NAME='" + rname + "'";
            ResultSet rs = state.executeQuery(query);
            while (rs.next()) {
                String name = rs.getString(1).trim();
                String type = getTypeField(rs.getInt(2));
                fieldName.addElement(name);
                fieldType.addElement(type);
            }
            state.close();
        } catch (Exception e) {
            GUIUtilities.displayErrorMessage(e.getMessage());
        }
        for (int i = 0; i < fieldName.size(); i++)
            try {
                Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                String s = "select distinct RDB$PRIVILEGE,RDB$GRANT_OPTION from RDB$USER_PRIVILEGES\n" +
                        "where (rdb$Relation_name='" + rname + "') and (rdb$user='" + userList.getSelectedValue().trim() + "') and\n" +
                        "(RDB$FIELD_NAME='" + fieldName.elementAt(i) + "')";
                ResultSet rs1 = st.executeQuery(s);
                Vector<Object> roleData = new Vector<Object>();
                roleData.add(fieldName.elementAt(i));
                roleData.add(fieldType.elementAt(i));
                for (int k = 0; k < 2; k++)
                    roleData.add(no);
                ((RoleTableModel) jTable2.getModel()).addRow(roleData);
                while (rs1.next()) {
                    String grant = rs1.getString(1).trim();
                    int ind = grants.indexOf(grant);
                    if (ind == 1)
                        if (rs1.getObject(2).equals(0)) {
                            jTable2.setValueAt(gr, i, 2);
                        } else
                            ((RoleTableModel) jTable2.getModel()).setValueAt(adm, i, 2);
                    if (ind == 5)
                        if (rs1.getObject(2).equals(0)) {
                            jTable2.setValueAt(gr, i, 3);
                        } else
                            ((RoleTableModel) jTable2.getModel()).setValueAt(adm, i, 3);

                }
                st.close();
            } catch (Exception e) {
                Log.error(e.getMessage());
            }
    }

    void getTables() {
        String query = "Select RDB$RELATION_NAME,RDB$SYSTEM_FLAG from RDB$RELATIONS" +
                " WHERE RDB$RELATION_TYPE != 1 order by 1";
        String type = objectBox.getItemAt(1);
        add_relations(query, type);
    }

    void getViews() {
        String query = "Select RDB$RELATION_NAME,RDB$SYSTEM_FLAG from RDB$RELATIONS" +
                " WHERE RDB$RELATION_TYPE = 1 order by 1";
        String type = objectBox.getItemAt(2);
        add_relations(query, type);
    }

    void getProcedures() {
        String query = "Select RDB$PROCEDURE_NAME,RDB$SYSTEM_FLAG from RDB$PROCEDURES order by 1";
        String type = objectBox.getItemAt(3);
        add_relations(query, type);
    }

    void removeRow(int i) {
        relName.remove(i);
        relType.remove(i);
        relSystem.remove(i);
        relGranted.remove(i);
    }

    void addRow(String name, String type, boolean system_flag, boolean grant_flag) {
        relName.add(name);
        relType.add(type);
        relSystem.add(system_flag);
        relGranted.add(grant_flag);
    }

    void add_relations(String query, String type) {
        try {
            Statement state = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
            ResultSet rs = state.executeQuery(query);
            Vector<String> rname = new Vector<>();
            Vector<Boolean> sflag = new Vector<>();
            while (rs.next()) {
                String name = rs.getString(1).trim();
                boolean system_flag = rs.getInt(2) == 1;
                rname.addElement(name);
                sflag.addElement(system_flag);
            }
            state.close();
            for (int i = 0; i < rname.size(); i++) {
                String name = rname.elementAt(i);
                boolean system_flag = sflag.elementAt(i);
                boolean granted_flag = false;
                if (!system_flag || system_flag == systemCheck.isSelected()) {
                    if (!jCheckBox1.isSelected() == name.contains(filterField.getText()))
                        addRow(name, type, system_flag, granted_flag);
                }
            }
        } catch (Exception e) {
            GUIUtilities.displayErrorMessage(e.getMessage());
        }
    }

    void setEnableElements(boolean enable) {
        enableElements = enable;
        databaseBox.setEnabled(enable);
        objectBox.setEnabled(enable);
        jCheckBox1.setEnabled(enable);
        filterBox.setEnabled(enable);
        filterField.setEnabled(enable);
        grant_all.setEnabled(enable);
        grant_g.setEnabled(enable);
        grant_g1.setEnabled(enable);
        grant_option_all.setEnabled(enable);
        grant_option_g.setEnabled(enable);
        grant_option_g1.setEnabled(enable);
        grant_option_v.setEnabled(enable);
        grant_option_v1.setEnabled(enable);
        grant_v.setEnabled(enable);
        grant_v1.setEnabled(enable);
        refreshButton.setEnabled(enable);
        revoke_all.setEnabled(enable);
        revoke_g.setEnabled(enable);
        revoke_g1.setEnabled(enable);
        revoke_v.setEnabled(enable);
        revoke_v1.setEnabled(enable);
        systemCheck.setEnabled(enable);
        userBox.setEnabled(enable);
        userList.setEnabled(enable);
        cancelButton.setVisible(!enable);
        jProgressBar1.setVisible(!enable);
        if (enable)
            jProgressBar1.setValue(0);
    }

    public void run() {
        int col;
        switch (act) {
            case CREATE_TABLE:
                load_table();
                break;
            case ALL_GRANTS_TO_ALL_OBJECTS: {
                jProgressBar1.setMaximum(relName.size());
                for (int row = 0; row < relName.size() && !enableElements; row++) {
                    jProgressBar1.setValue(row);
                    for (col = 1; col < headers.length; col++)
                        grant_on_role(1, row, col);
                }
                jProgressBar1.setValue(0);
                setEnableElements(true);
            }
            break;
            case ALL_GRANTS_TO_ALL_OBJECTS_WITH_GRANT_OPTION:
                jProgressBar1.setMaximum(relName.size());
                for (int row = 0; row < relName.size() && !enableElements; row++) {
                    jProgressBar1.setValue(row);
                    for (col = 1; col < headers.length; col++)
                        grant_on_role(2, row, col);
                }
                jProgressBar1.setValue(0);
                setEnableElements(true);
                break;
            case NO_ALL_GRANTS_TO_ALL_OBJECTS:
                jProgressBar1.setMaximum(relName.size());
                for (int row = 0; row < relName.size() && !enableElements; row++) {
                    jProgressBar1.setValue(row);
                    for (col = 1; col < headers.length; col++)
                        grant_on_role(0, row, col);
                }
                jProgressBar1.setValue(0);
                setEnableElements(true);
                break;
            case GRANT_TO_ALL_OBJECTS:
                col = tablePrivileges.getSelectedColumn();
                jProgressBar1.setMaximum(relName.size());
                if (col > 0)
                    for (int row = 0; row < relName.size() && !enableElements; row++) {
                        jProgressBar1.setValue(row);
                        grant_on_role(1, row, col);
                    }
                jProgressBar1.setValue(0);
                setEnableElements(true);
                break;
            case GRANT_TO_ALL_OBJECTS_WITH_GRANT_OPTION:
                col = tablePrivileges.getSelectedColumn();
                jProgressBar1.setMaximum(relName.size());
                if (col > 0)
                    for (int row = 0; row < relName.size() && !enableElements; row++) {
                        jProgressBar1.setValue(row);
                        grant_on_role(2, row, col);
                    }
                jProgressBar1.setValue(0);
                setEnableElements(true);
                break;
            case NO_GRANT_TO_ALL_OBJECTS:
                col = tablePrivileges.getSelectedColumn();
                jProgressBar1.setMaximum(relName.size());
                if (col > 0)
                    for (int row = 0; row < relName.size() && !enableElements; row++) {
                        jProgressBar1.setValue(row);
                        grant_on_role(0, row, col);
                    }
                jProgressBar1.setValue(0);
                setEnableElements(true);
                break;
        }
    }

    void grant_on_role(int grantt, int row, int col) {
        if (row < tablePrivileges.getRowCount())
            switch (grantt) {
                case 0:
                    try {

                        Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                        if (!relType.elementAt(row).equals(objectBox.getItemAt(3))) {
                            if (!headers[col].equals("Execute")) {
                                st.execute("REVOKE " + headers[col] + " ON \"" + relName.elementAt(row) + "\" FROM \"" + userList.getSelectedValue() + "\";");
                                tablePrivileges.setValueAt(no, row, col);
                                st.close();
                            }
                        } else if (headers[col].equals("Execute")) {
                            st.execute("REVOKE " + headers[col] + " ON PROCEDURE \"" + relName.elementAt(row) + "\" FROM \"" + userList.getSelectedValue() + "\";");
                            tablePrivileges.setValueAt(no, row, col);
                            st.close();
                        }

                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                    }
                    break;
                case 1:
                    if (((Icon) tablePrivileges.getValueAt(row, col)).equals(adm)) {
                        try {

                            Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                            if (!relType.elementAt(row).equals(objectBox.getItemAt(3))) {
                                if (!headers[col].equals("Execute")) {
                                    st.execute("REVOKE " + headers[col] + " ON \"" + relName.elementAt(row) + "\" FROM \"" + userList.getSelectedValue() + "\";");
                                    tablePrivileges.setValueAt(no, row, col);
                                    st.close();
                                }
                            } else if (headers[col].equals("Execute")) {
                                st.execute("REVOKE " + headers[col] + " ON PROCEDURE \"" + relName.elementAt(row) + "\" FROM \"" + userList.getSelectedValue() + "\";");
                                tablePrivileges.setValueAt(no, row, col);
                                st.close();
                            }

                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        }

                        try {
                            Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                            if (!relType.elementAt(row).equals(objectBox.getItemAt(3))) {
                                if (!headers[col].equals("Execute")) {
                                    st.execute("GRANT " + headers[col] + " ON \"" + relName.elementAt(row) + "\" TO \"" + userList.getSelectedValue() + "\";");
                                    tablePrivileges.setValueAt(gr, row, col);
                                    st.close();
                                }
                            } else if (headers[col].equals("Execute")) {
                                st.execute("GRANT " + headers[col] + " ON PROCEDURE \"" + relName.elementAt(row) + "\" TO \"" + userList.getSelectedValue() + "\";");
                                tablePrivileges.setValueAt(gr, row, col);
                                st.close();
                            }

                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        }

                    } else
                        try {
                            Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                            if (!relType.elementAt(row).equals(objectBox.getItemAt(3))) {
                                if (!headers[col].equals("Execute")) {
                                    st.execute("GRANT " + headers[col] + " ON \"" + relName.elementAt(row) + "\" TO \"" + userList.getSelectedValue() + "\";");
                                    tablePrivileges.setValueAt(gr, row, col);
                                    st.close();
                                }
                            } else if (headers[col].equals("Execute")) {
                                st.execute("GRANT " + headers[col] + " ON PROCEDURE \"" + relName.elementAt(row) + "\" TO \"" + userList.getSelectedValue() + "\";");
                                tablePrivileges.setValueAt(gr, row, col);
                                st.close();
                            }
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        }
                    break;
                case 2:
                    try {
                        Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                        if (!relType.elementAt(row).equals(objectBox.getItemAt(3))) {
                            if (!headers[col].equals("Execute")) {
                                st.execute("GRANT " + headers[col] + " ON \"" + relName.elementAt(row) + "\" TO \"" + userList.getSelectedValue() + "\" WITH GRANT OPTION;");
                                tablePrivileges.setValueAt(adm, row, col);
                                st.close();
                            }
                        } else if (headers[col].equals("Execute")) {
                            st.execute("GRANT " + headers[col] + " ON PROCEDURE \"" + relName.elementAt(row) + "\" TO \"" + userList.getSelectedValue() + "\" WITH GRANT OPTION;");
                            tablePrivileges.setValueAt(adm, row, col);
                            st.close();
                        }
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                    }
                    break;
            }
    }

    void grant_on_role(int grantt, int row, int col, int row2) {
        if (row < tablePrivileges.getRowCount())
            switch (grantt) {
                case 0:
                    try {
                        Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                        st.execute("REVOKE " + headers2[col] + " (" + fieldName.elementAt(row2) + ")"
                                + " ON \"" + relName.elementAt(row) + "\" FROM \"" + userList.getSelectedValue() + "\";");
                        jTable2.setValueAt(no, row2, col);
                        st.close();
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                    }
                    break;
                case 1:
                    if (((Icon) jTable2.getValueAt(row2, col)).equals(adm)) {
                        try {
                            Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                            st.execute("REVOKE " + headers2[col] + " (" + fieldName.elementAt(row2) + ")"
                                    + " ON \"" + relName.elementAt(row) + "\" FROM \"" + userList.getSelectedValue() + "\";");
                            jTable2.setValueAt(no, row2, col);
                            st.close();
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        }

                        try {
                            Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                            st.execute("GRANT " + headers2[col] + " (" + fieldName.elementAt(row2) + ")"
                                    + " ON \"" + relName.elementAt(row) + "\" TO \"" + userList.getSelectedValue() + "\";");
                            jTable2.setValueAt(gr, row2, col);
                            st.close();
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        }

                    } else
                        try {
                            Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                            st.execute("GRANT " + headers2[col] + " (" + fieldName.elementAt(row2) + ")"
                                    + " ON \"" + relName.elementAt(row) + "\" TO \"" + userList.getSelectedValue() + "\";");
                            jTable2.setValueAt(gr, row2, col);
                            st.close();
                        } catch (Exception e) {
                            System.out.println(e.getMessage());
                        }
                    break;
                case 2:
                    try {
                        Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
                        st.execute("GRANT " + headers2[col] + " (" + fieldName.elementAt(row2) + ")"
                                + " ON \"" + relName.elementAt(row) + "\" TO \"" + userList.getSelectedValue() + "\" WITH GRANT OPTION;");
                        jTable2.setValueAt(adm, row2, col);
                        st.close();
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                    }
                    break;
            }
    }

    void execute_thread() {
        if (enableElements) {
            setEnableElements(false);
            Runnable r = new ThreadOfGrantManager(this);
            Thread t = new Thread(r);
            t.start();
        }
    }

    boolean isGranted(String name, String user) {
        try {
            Statement st = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY, ResultSet.HOLD_CURSORS_OVER_COMMIT);
            String s = "select distinct RDB$PRIVILEGE,RDB$GRANT_OPTION from RDB$USER_PRIVILEGES\n" +
                    "where (rdb$Relation_name='" + name + "') and (rdb$user='" + user + "')";
            ResultSet rs1 = st.executeQuery(s);
            boolean isGranted = rs1.next();
            st.close();
            return isGranted;
        } catch (Exception e) {
            System.out.println(e.getMessage());
            return false;
        }

    }

    void setVisiblePanelOfTable(boolean flag) {
        if (flag) {
            int row = tablePrivileges.getSelectedRow();
            labelTable.setText("Columns of [" + relName.elementAt(row) + "]");
            load_table2(relName.elementAt(row));
            obj_index = row;
        } else {
            labelTable.setText("Columns of ");
            jTable2.setModel(new RoleTableModel(headers2, 0));
        }

    }

    String getTypeField(int type) {
        switch (type) {
            case 7:
                return "SMALLINT";
            case 8:
                return "INTEGER";
            case 10:
                return "FLOAT";
            case 12:
                return "DATE";
            case 13:
                return "TIME";
            case 14:
                return "CHAR";
            case 16:
                return "BIGINT";
            case 27:
                return "DOUBLE PRECISION";
            case 35:
                return "TIMESTAMP";
            case 37:
                return "VARCHAR";
            case 261:
                return "BLOB";
            default:
                return "UNKNOWN";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cancelButton;
    private JComboBox<String> databaseBox;
    private JPanel downPanel;
    private JComboBox<String> filterBox;
    private JTextField filterField;
    private JButton grant_all;
    private JButton grant_g;
    private JButton grant_g1;
    private JButton grant_option_all;
    private JButton grant_option_g;
    private JButton grant_option_g1;
    private JButton grant_option_v;
    private JButton grant_option_v1;
    private JButton grant_v;
    private JButton grant_v1;
    private JCheckBox jCheckBox1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JProgressBar jProgressBar1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JTable jTable2;
    private JLabel labelTable;
    private JPanel leftPanel;
    private JComboBox<String> objectBox;
    private JButton refreshButton;
    private JButton revoke_all;
    private JButton revoke_g;
    private JButton revoke_g1;
    private JButton revoke_v;
    private JButton revoke_v1;
    private JPanel rightPanel;
    private JCheckBox systemCheck;
    private JTable tablePrivileges;
    private JPanel upPanel;
    private JComboBox<String> userBox;
    private JList<String> userList;
    // End of variables declaration//GEN-END:variables

}
