/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.executequery.gui.browser;

import org.executequery.databasemediators.DatabaseConnection;
import org.executequery.repository.DatabaseConnectionRepository;
import org.executequery.repository.RepositoryCache;
import org.firebirdsql.management.FBUserManager;
import org.firebirdsql.management.User;
import org.firebirdsql.management.UserManager;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.List;
import java.util.Map;

/**
 *
 * @author МишаИОля
 */
public class UserManagerPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserManagerPanel
     */
    public UserManagerPanel() {



        //userManager.
        initComponents();
        listConnections=((DatabaseConnectionRepository) RepositoryCache.load(DatabaseConnectionRepository.REPOSITORY_ID)).findAll();
        this.userManager = new FBUserManager();
        for(DatabaseConnection dc:listConnections)
        {
            databaseBox.addItem(dc.getName());
            if (dc.isConnected())
                databaseBox.setSelectedItem(dc.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        databaseLabel = new javax.swing.JLabel();
        serverLabel = new javax.swing.JLabel();
        databaseBox = new javax.swing.JComboBox<>();
        serverBox = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        usersPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        addUserButton = new javax.swing.JButton();
        editUserButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        refreshUsersButton = new javax.swing.JButton();
        rolesPanel = new javax.swing.JPanel();
        membershipPanel = new javax.swing.JPanel();

        setName(""); // NOI18N

        jPanel1.setName("upPanel"); // NOI18N

        databaseLabel.setText("database");

        serverLabel.setText("server");

        databaseBox.setEditable(true);
        databaseBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseBoxActionPerformed(evt);
            }
        });

        serverBox.setEditable(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(databaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(serverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(serverBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(databaseBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(databaseLabel)
                                        .addComponent(databaseBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(serverLabel)
                                        .addComponent(serverBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.setToolTipText("");

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "User name", "First name", "Middle name", "Last name", "AC"
                }
        ));
        jScrollPane1.setViewportView(usersTable);

        addUserButton.setText("Add");

        editUserButton.setText("Edit");

        deleteUserButton.setText("Delete");

        refreshUsersButton.setText("Refresh");

        javax.swing.GroupLayout usersPanelLayout = new javax.swing.GroupLayout(usersPanel);
        usersPanel.setLayout(usersPanelLayout);
        usersPanelLayout.setHorizontalGroup(
                usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(usersPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addUserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editUserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteUserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(refreshUsersButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );
        usersPanelLayout.setVerticalGroup(
                usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(usersPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(addUserButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editUserButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteUserButton)
                                .addGap(18, 18, 18)
                                .addComponent(refreshUsersButton)
                                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Users", usersPanel);

        javax.swing.GroupLayout rolesPanelLayout = new javax.swing.GroupLayout(rolesPanel);
        rolesPanel.setLayout(rolesPanelLayout);
        rolesPanelLayout.setHorizontalGroup(
                rolesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 465, Short.MAX_VALUE)
        );
        rolesPanelLayout.setVerticalGroup(
                rolesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 180, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Roles", rolesPanel);

        javax.swing.GroupLayout membershipPanelLayout = new javax.swing.GroupLayout(membershipPanel);
        membershipPanel.setLayout(membershipPanelLayout);
        membershipPanelLayout.setHorizontalGroup(
                membershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 465, Short.MAX_VALUE)
        );
        membershipPanelLayout.setVerticalGroup(
                membershipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 180, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Membership", membershipPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Users");
    }// </editor-fold>                        
    private void databaseBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if(databaseBox.getItemAt(databaseBox.getSelectedIndex())!="") {
            serverBox.removeAllItems();
            serverBox.addItem(listConnections.get(databaseBox.getSelectedIndex()).getHost());
        }
        userManager.setDatabase(listConnections.get(databaseBox.getSelectedIndex()).getSourceName());
        userManager.setUser(listConnections.get(databaseBox.getSelectedIndex()).getUserName());
        userManager.setPassword(listConnections.get(databaseBox.getSelectedIndex()).getPassword());
        userManager.setHost(listConnections.get(databaseBox.getSelectedIndex()).getHost());
        userManager.setPort(listConnections.get(databaseBox.getSelectedIndex()).getPortInt());
        //userManager.setCharSet(listConnections.get(databaseBox.getSelectedIndex()).getCharset());
        try {
            users = userManager.getUsers();
            usersTable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                            "User name", "First name", "Middle name", "Last name", "AC"
                    }
            ));
            for(User u:users.values())
            {
                Object[] rowData=new Object[]{u.getUserName(),u.getFirstName(),u.getMiddleName(),u.getLastName(),u.getUserId()};
                ((DefaultTableModel) usersTable.getModel()).addRow(rowData);
            }
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }

    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addUserButton;
    private javax.swing.JComboBox<String> databaseBox;
    private javax.swing.JLabel databaseLabel;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JButton editUserButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel membershipPanel;
    private javax.swing.JButton refreshUsersButton;
    private javax.swing.JPanel rolesPanel;
    private javax.swing.JComboBox<String> serverBox;
    private javax.swing.JLabel serverLabel;
    private javax.swing.JPanel usersPanel;
    private javax.swing.JTable usersTable;
    // End of variables declaration                   
    public static final String TITLE = "User manager";

    /**
     * This objects icon as an internal frame
     */
    public static final String FRAME_ICON = "user_manager_16.png";
    UserManager userManager;
    private BrowserController controller;
    List<DatabaseConnection> listConnections;
    Map<String,User> users;

}
