package org.executequery.gui.browser.managment;

import biz.redsoft.IFBUser;
import org.executequery.GUIUtilities;
import org.executequery.gui.browser.UserManagerPanel;
import org.executequery.localization.Bundles;
import org.underworldlabs.swing.NumberTextField;

/**
 * Created by mikhan808 on 20.02.2017.
 */
public class WindowAddUser extends javax.swing.JPanel {

  /**
   * Creates new form WindowAddUser
   *
   * @param u
   */
  public WindowAddUser(UserManagerPanel u) {

    initComponents();
    ump = u;
    edit = false;
  }

  IFBUser user;
  boolean edit;

  public WindowAddUser(UserManagerPanel u, IFBUser user, String description) {

    initComponents();
    ump = u;
    edit = true;
    this.user = user;
    nameTextField.setText(user.getUserName());
    nameTextField.setEnabled(false);
    firstNameField.setText(user.getFirstName());
    middleNameField.setText(user.getMiddleName());
    lastNameField.setText(user.getLastName());
    groupIDField.setText(Integer.toString(user.getGroupId()));
    userIDField.setText(Integer.toString(user.getUserId()));
    descriptionField.setText(description);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    nameTextField = new javax.swing.JTextField();
    passTextField = new javax.swing.JPasswordField();
    confirmField = new javax.swing.JPasswordField();
    firstNameField = new javax.swing.JTextField();
    middleNameField = new javax.swing.JTextField();
    lastNameField = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    descriptionField = new javax.swing.JTextArea();
    userIDField = new NumberTextField();
    groupIDField = new NumberTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    descriptionField.setColumns(20);
    descriptionField.setRows(5);
    jScrollPane1.setViewportView(descriptionField);

    userIDField.setText("0");

    groupIDField.setText("0");

    jLabel1.setText(bundleString("UserName"));

    jLabel2.setText(bundleString("Password"));

    jLabel3.setText(bundleString("ConfirmPassword"));

    jLabel4.setText(bundleString("FirstName"));

    jLabel5.setText(bundleString("MiddleName"));

    jLabel6.setText(bundleString("LastName"));

    jLabel7.setText(bundleString("UserID"));

    jLabel8.setText(bundleString("GroupID"));

    jLabel9.setText(bundleString("Description"));

    okButton.setText(bundleString("OK"));
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    cancelButton.setText(bundleString("Cancel"));
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTextField)
                            .addComponent(passTextField)
                            .addComponent(confirmField)
                            .addComponent(firstNameField)
                            .addComponent(middleNameField)
                            .addComponent(lastNameField,javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(groupIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addGap(19, 19, 19))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(confirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(groupIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addGap(10,10,10))
    );

    //pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    if(!nameTextField.getText().equals(""))
    {
    if (new String(passTextField.getPassword()).equals(new String(confirmField.getPassword()))) {
      ump.userAdd.setUserName(nameTextField.getText());
      ump.userAdd.setFirstName(firstNameField.getText());
      ump.userAdd.setMiddleName(middleNameField.getText());
      ump.userAdd.setLastName(lastNameField.getText());
      ump.userAdd.setUserId(Integer.parseInt(userIDField.getText()));
      ump.userAdd.setGroupId(Integer.parseInt(groupIDField.getText()));
      if (edit) {
        if(passTextField.getPassword().length>0)
          ump.userAdd.setPassword(new String(passTextField.getPassword()));
        ump.editUser(descriptionField.getText());
        GUIUtilities.closeSelectedTab();
      } else {
        if(passTextField.getPassword().length>0) {
          ump.userAdd.setPassword(new String(passTextField.getPassword()));
          ump.addUser(descriptionField.getText());
          GUIUtilities.closeSelectedTab();
        }
        else{
          GUIUtilities.displayErrorMessage(bundleString("error.empty-pwd"));
        }

      }

    } else {
      GUIUtilities.displayErrorMessage(bundleString("error.pwds-not-match"));
    }
    }
    else
    {
      GUIUtilities.displayErrorMessage(bundleString("error.empty-name"));
    }
  }//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    GUIUtilities.closeSelectedTab();
  }//GEN-LAST:event_cancelButtonActionPerformed
  private String bundleString(String key)
  {
    return Bundles.get(getClass(),key);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JPasswordField confirmField;
  private javax.swing.JTextArea descriptionField;
  private javax.swing.JTextField firstNameField;
  private NumberTextField groupIDField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField lastNameField;
  private javax.swing.JTextField middleNameField;
  private javax.swing.JTextField nameTextField;
  private javax.swing.JButton okButton;
  private javax.swing.JPasswordField passTextField;
  private NumberTextField userIDField;
  // End of variables declaration//GEN-END:variables
  UserManagerPanel ump;
}

